PIC EQU 20H
EOI EQU 20H
N_F10 EQU 10

ORG 40
IP_F10   DW   RUT_F10

ORG 2000H
CLI ; CLI DESACTIVO INTERRUPCIONES
MOV AL, 0FEH ; MUEVO A AL LA POSICION 11111110 EN BINARIO;
OUT PIC+1, AL ; PIC: registro IMR
MOV AL, N_F10; MUEVO A AL 10
OUT PIC+4, AL ; PIC: registro INT0
MOV DX, 0; INICIO CONTADOR
STI; STI ACTIVO INTERRUPCIONES
LAZO: 	JMP LAZO

ORG 3000H
RUT_F10: 	PUSH AX; APILO AX
INC DX	; SUMO UNO EN DX
MOV AL, EOI; MUEVO A AL 20H
OUT EOI, AL ; PIC: registro EOI
POP AX; DESAPILO AX
IRET
END
