TIMER EQU 10H
PIC EQU 20H
IMR EQU 21H ; ENMASCARA INTERRUPCIONES CON 1
TIMER_PIC EQU 25H
N_F10 EQU 10 ;  IP_CLK = N_CLK*4
N_TIMER EQU 11

ORG 40
IP_F10 DW RUT_F10
ORG 44
IP_TIMER DW RUT_TIMER

ORG 1000H
SEG DB 33H
	DB 30H
	
ORG 3000H
RUT_TIMER:MOV CL, SEG+1
	CMP CL, 30H
	JZ AMBOS
	JNZ SOLOUNIDAD
SOLOUNIDAD: DEC CL
			MOV SEG+1,CL
			JMP FIN
AMBOS: MOV SEG+1, 39H
	   MOV CL,SEG
	   DEC CL
	   MOV SEG,CL
	   JMP FIN
FIN:MOV BX, OFFSET SEG
	MOV AL,2
	INT 7
	MOV AL,0
	OUT TIMER,AL
	MOV AL,PIC
	OUT PIC,AL
	IRET
RUT_F10: IN AL,PIC+1
		 XOR AL,00000010B
		 OUT PIC+1,AL
		 MOV AL,PIC
		 OUT PIC,AL
		 IRET
		 
ORG 2000H
CLI
MOV AL,11111100B ; DESENMASCARA F10 Y TIMER
OUT PIC+1,AL ; ACTUALIZA IMR
;CONFIGURA TIMER
MOV AL, N_TIMER
OUT PIC+5, AL
MOV AL,5
OUT TIMER+1,AL
;CONFIGURA F10
MOV AL,N_F10
OUT PIC+4,AL
STI
LOOP:JMP LOOP 
INT 0
END


